# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Mathias_TDS754D_Logiciel.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 729)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TDS754D_qlbl = QtWidgets.QLabel(self.centralwidget)
        self.TDS754D_qlbl.setGeometry(QtCore.QRect(30, 30, 55, 16))
        self.TDS754D_qlbl.setObjectName("TDS754D_qlbl")
        self.InitGPIB_qpbt = QtWidgets.QPushButton(self.centralwidget)
        self.InitGPIB_qpbt.setGeometry(QtCore.QRect(480, 30, 81, 31))
        self.InitGPIB_qpbt.setObjectName("InitGPIB_qpbt")
        self.TDS754D_IDN_qledit = QtWidgets.QLineEdit(self.centralwidget)
        self.TDS754D_IDN_qledit.setGeometry(QtCore.QRect(120, 30, 331, 22))
        self.TDS754D_IDN_qledit.setObjectName("TDS754D_IDN_qledit")
        self.TDS754D_ADR_qledit = QtWidgets.QLineEdit(self.centralwidget)
        self.TDS754D_ADR_qledit.setGeometry(QtCore.QRect(90, 30, 31, 22))
        self.TDS754D_ADR_qledit.setObjectName("TDS754D_ADR_qledit")
        self.Quit_qpbt = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_qpbt.setGeometry(QtCore.QRect(590, 30, 81, 31))
        self.Quit_qpbt.setObjectName("Quit_qpbt")
        self.Acquire_data_qpbt = QtWidgets.QPushButton(self.centralwidget)
        self.Acquire_data_qpbt.setGeometry(QtCore.QRect(90, 90, 201, 28))
        self.Acquire_data_qpbt.setObjectName("Acquire_data_qpbt")
        self.SaveFileName_qledit = QtWidgets.QLineEdit(self.centralwidget)
        self.SaveFileName_qledit.setGeometry(QtCore.QRect(150, 150, 381, 22))
        self.SaveFileName_qledit.setObjectName("SaveFileName_qledit")
        self.FileLoad_qpbt = QtWidgets.QPushButton(self.centralwidget)
        self.FileLoad_qpbt.setGeometry(QtCore.QRect(540, 150, 61, 21))
        self.FileLoad_qpbt.setObjectName("FileLoad_qpbt")
        self.LblSaveFileName_qlbl = QtWidgets.QLabel(self.centralwidget)
        self.LblSaveFileName_qlbl.setGeometry(QtCore.QRect(0, 150, 141, 16))
        self.LblSaveFileName_qlbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LblSaveFileName_qlbl.setObjectName("LblSaveFileName_qlbl")
        self.FileSaveAs_qpbt = QtWidgets.QPushButton(self.centralwidget)
        self.FileSaveAs_qpbt.setGeometry(QtCore.QRect(610, 150, 61, 21))
        self.FileSaveAs_qpbt.setObjectName("FileSaveAs_qpbt")
        self.Description_qledit = QtWidgets.QLineEdit(self.centralwidget)
        self.Description_qledit.setGeometry(QtCore.QRect(150, 200, 341, 22))
        self.Description_qledit.setObjectName("Description_qledit")
        self.LblDescription_qlbl = QtWidgets.QLabel(self.centralwidget)
        self.LblDescription_qlbl.setGeometry(QtCore.QRect(0, 200, 141, 16))
        self.LblDescription_qlbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LblDescription_qlbl.setObjectName("LblDescription_qlbl")
        self.Date_qledit = QtWidgets.QLineEdit(self.centralwidget)
        self.Date_qledit.setGeometry(QtCore.QRect(500, 200, 171, 22))
        self.Date_qledit.setObjectName("Date_qledit")
        self.Plot_data_qpbt = QtWidgets.QPushButton(self.centralwidget)
        self.Plot_data_qpbt.setGeometry(QtCore.QRect(380, 90, 201, 28))
        self.Plot_data_qpbt.setObjectName("Plot_data_qpbt")
        self.Channel2_Data_qtedit = QtWidgets.QTextEdit(self.centralwidget)
        self.Channel2_Data_qtedit.setGeometry(QtCore.QRect(190, 290, 131, 371))
        self.Channel2_Data_qtedit.setObjectName("Channel2_Data_qtedit")
        self.Channel1_qlbl = QtWidgets.QLabel(self.centralwidget)
        self.Channel1_qlbl.setGeometry(QtCore.QRect(4, 250, 161, 20))
        self.Channel1_qlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Channel1_qlbl.setObjectName("Channel1_qlbl")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 270, 681, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(160, 250, 20, 431))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Channel1_Data_qtedit = QtWidgets.QTextEdit(self.centralwidget)
        self.Channel1_Data_qtedit.setGeometry(QtCore.QRect(20, 290, 131, 371))
        self.Channel1_Data_qtedit.setObjectName("Channel1_Data_qtedit")
        self.Channel2_qlbl = QtWidgets.QLabel(self.centralwidget)
        self.Channel2_qlbl.setGeometry(QtCore.QRect(170, 250, 151, 20))
        self.Channel2_qlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Channel2_qlbl.setObjectName("Channel2_qlbl")
        self.Channel3_qlbl = QtWidgets.QLabel(self.centralwidget)
        self.Channel3_qlbl.setGeometry(QtCore.QRect(344, 250, 161, 20))
        self.Channel3_qlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Channel3_qlbl.setObjectName("Channel3_qlbl")
        self.Channel4_qlbl = QtWidgets.QLabel(self.centralwidget)
        self.Channel4_qlbl.setGeometry(QtCore.QRect(510, 250, 161, 20))
        self.Channel4_qlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Channel4_qlbl.setObjectName("Channel4_qlbl")
        self.Channel3_Data_qtedit = QtWidgets.QTextEdit(self.centralwidget)
        self.Channel3_Data_qtedit.setGeometry(QtCore.QRect(360, 290, 131, 371))
        self.Channel3_Data_qtedit.setObjectName("Channel3_Data_qtedit")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(500, 250, 20, 431))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Channel4_Data_qtedit = QtWidgets.QTextEdit(self.centralwidget)
        self.Channel4_Data_qtedit.setGeometry(QtCore.QRect(530, 290, 131, 371))
        self.Channel4_Data_qtedit.setObjectName("Channel4_Data_qtedit")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(330, 250, 20, 431))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TDS754D_qlbl.setText(_translate("MainWindow", "TDS754D"))
        self.InitGPIB_qpbt.setText(_translate("MainWindow", "InitGPIB"))
        self.TDS754D_ADR_qledit.setText(_translate("MainWindow", "1"))
        self.Quit_qpbt.setText(_translate("MainWindow", "Quit"))
        self.Acquire_data_qpbt.setText(_translate("MainWindow", "Acquire data"))
        self.FileLoad_qpbt.setText(_translate("MainWindow", "Load"))
        self.LblSaveFileName_qlbl.setText(_translate("MainWindow", "Fichier de sauvegarde"))
        self.FileSaveAs_qpbt.setText(_translate("MainWindow", "SaveAs"))
        self.LblDescription_qlbl.setText(_translate("MainWindow", "Description"))
        self.Plot_data_qpbt.setText(_translate("MainWindow", "Plot data"))
        self.Channel1_qlbl.setText(_translate("MainWindow", "Channel 1 (V)"))
        self.Channel2_qlbl.setText(_translate("MainWindow", "Channel 2 (V)"))
        self.Channel3_qlbl.setText(_translate("MainWindow", "Channel 3 (V)"))
        self.Channel4_qlbl.setText(_translate("MainWindow", "Channel 4 (V)"))

