# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_form.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 763)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 380, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.COMMANDS = QtWidgets.QLabel(self.centralwidget)
        self.COMMANDS.setGeometry(QtCore.QRect(60, 50, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.COMMANDS.setFont(font)
        self.COMMANDS.setObjectName("COMMANDS")
        self.DAC_SELECTOR = QtWidgets.QComboBox(self.centralwidget)
        self.DAC_SELECTOR.setGeometry(QtCore.QRect(230, 390, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DAC_SELECTOR.setFont(font)
        self.DAC_SELECTOR.setObjectName("DAC_SELECTOR")
        self.DAC_SELECTOR.addItem("")
        self.DAC_SELECTOR.addItem("")
        self.DAC_SELECTOR.addItem("")
        self.DAC_SELECTOR.addItem("")
        self.VALUE_INPUT = QtWidgets.QLineEdit(self.centralwidget)
        self.VALUE_INPUT.setGeometry(QtCore.QRect(400, 390, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.VALUE_INPUT.setFont(font)
        self.VALUE_INPUT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VALUE_INPUT.setObjectName("VALUE_INPUT")
        self.VALUE_INPUT.setInputMask("99999")
        self.VALUE_INPUT.setMaxLength(5)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 360, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(60, 200, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.Time_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Time_input.setGeometry(QtCore.QRect(230, 200, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Time_input.setFont(font)
        self.Time_input.setObjectName("Time_input")
        self.Time_input.setInputMask('9999')
        self.Time_input.setMaxLength(5)
        self.Time_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 170, 55, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 170, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.time_scale = QtWidgets.QComboBox(self.centralwidget)
        self.time_scale.setGeometry(QtCore.QRect(520, 200, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.time_scale.setFont(font)
        self.time_scale.setObjectName("time_scale")
        self.time_scale.addItem("")
        self.time_scale.addItem("")
        self.time_scale.addItem("")
        self.step_time = QtWidgets.QPushButton(self.centralwidget)
        self.step_time.setGeometry(QtCore.QRect(700, 180, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.step_time.setFont(font)
        self.step_time.setObjectName("step_time")
        self.Export = QtWidgets.QPushButton(self.centralwidget)
        self.Export.setGeometry(QtCore.QRect(740, 630, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Export.setFont(font)
        self.Export.setObjectName("Export")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ADD "))
        self.COMMANDS.setText(_translate("MainWindow", "Number of Commands : 0"))
        self.DAC_SELECTOR.setItemText(0, _translate("MainWindow", "DAC1"))
        self.DAC_SELECTOR.setItemText(1, _translate("MainWindow", "DAC2"))
        self.DAC_SELECTOR.setItemText(2, _translate("MainWindow", "DAC3"))
        self.DAC_SELECTOR.setItemText(3, _translate("MainWindow", "DAC4"))
        self.VALUE_INPUT.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "VALUE (mV)"))
        self.time.setText(_translate("MainWindow", "t = 0"))
        
       # self.Time_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
#"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
#"p, li { white-space: pre-wrap; }\n"
#"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
#"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "time step"))
        self.time_scale.setItemText(0, _translate("MainWindow", "ms"))
        self.time_scale.setItemText(1, _translate("MainWindow", "us"))
        self.time_scale.setItemText(2, _translate("MainWindow", "s"))
        self.step_time.setText(_translate("MainWindow", "STEP TIME"))
        self.Export.setText(_translate("MainWindow", "EXPORT"))

